### ISSUE TITLE
React-native-maps component within shoutem/ui overrules root level react-native-maps

### ISSUE THREAD

**Issue by nillo** [shoutem/ui#58]
The react-native-maps component that is supplied with shoutem (version 0.6.0) gets imported by the packager, while the current version on root leven 0.8.2 gets ignored. causing strange react native maps error, the only quick solution was to remove react-native-maps from the shoutem package.

How can i prevent the packager from the preferring the included to shoutem react-native-maps, above the one i have as a dependency of my overall project. (root/node_modules) ?

(everything is working fine and well, but i have to make changes to your npm package, which i actually don't want to do, so i can easily update later on)

**Comment by nillo** [comment]
When exploring your package.json, i see u still use:
github:5minutes/react-native-maps#friends-with-28 as the react-native-maps repo.

If i remember correctly this was to solve some dependency issue, where react native maps failed on android for react native 28+,

this issue was solved a while ago, i can't remember in what version it was updated, but meanwhile react-native-maps has been updated to 0.82, so maybe u can update it within shoutem as well, for those who need it

**Comment by nilsonivano** [comment]
Hey @nillo , thanks for trying to solve the same problem that I'm having with Shoutem package.
Can you explain how did you removed react-native-maps from the shoutem package?

**Comment by SoHotSoup** [comment]
@Vunovati Could you please take a look at this one?

**Comment by nillo** [comment]
@nilsonivano, i just removed react-native-maps, from the node_modules folder within the shoutem ui folder. because my project has react-native-maps as a dependency itself, it will just fall back to 
root/node_modules/react-native-maps
instead of 
root/node_modules/@shoutem/ui/node_modules/react-native-maps

strange enough, i redid this progress because i forgot what i did. so i just reinstalled shoutem, and did it all over again, en everything is exactly the same as it was before, 

but nou the react-native packager DOES use:

> root/node_modules/react-native-maps
 
and ignores 

> root/node_modules/@shoutem/ui/node_modules/react-native-maps.
(weird....)

Weird, but a quick fix: if react-native-maps, is already part of ur project, just delete it from @shoutem/ui/node_modules/ (react-native-maps)

**Comment by nilsonivano** [comment]
@Vunovati, thanks for the commit. I've just installed the beta version using npm install @shoutem/ui@beta but I still getting many errors loading react-native-maps

index.android.bundle?platform=android&dev=true&hot=true&minify=false:28510 Warning: Native component for "AIRMapMarker" does not exist
index.android.bundle?platform=android&dev=true&hot=true&minify=false:28510 Warning: Native component for "AIRMapPolyline" does not exist

Can you help me with this problem?

@nillo , did you solved your problem with this commit?

**Comment by SoHotSoup** [comment]
@nilsonivano This is not published to npm yet.

**Comment by Vunovati** [comment]
@nilsonivano if you can't wait for the next ui-toolkit release you can always get the package directly from the github repo.

Just add

`"@shoutem/ui": "shoutem/ui#develop",`

instead of `"@shoutem/ui": "0.9.1"`

**Comment by nilsonivano** [comment]
@vuvonati I got the #develop package, but I'm still getting this kind of error on installation process

{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/@shoutem/animation/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/@shoutem/theme/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/babel-plugin-transform-decorators-legacy/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/buffer/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/events/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/html-entities/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/react-native-lightbox/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/react-native-maps/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/react-native-share/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/react-native-vector-icons/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/stream/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/nilsonivano/lemeatApp/node_modules/@shoutem/ui/node_modules/tinycolor2/package.json'] code: 'MODULE_NOT_FOUND' }

**Comment by SoHotSoup** [comment]
@nilsonivano we are working on that, it has something with `react-native link` it tries to find dependencies in wrong directory... but it everything works no matter that error is shown during the npm post install.

**Comment by Vunovati** [comment]
The postinstall react-native link is confused where the newly installed packages are. Don't worry about that, they are installed in `/Users/nilsonivano/lemeatApp/node_modules/` . just run `react-native link` afterwards.

**Comment by beydogan** [comment]
@nillo you saved my day, i have the same problem. Using `shoutem/ui#develop` didn't solve my problem. I had to delete react-native-maps folder in "node_modules/@shoutem/ui/node_modules`
